<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>SISL User Manual</title>

		<meta name="color-scheme" content="light dark">
		<meta name="robots" content="noindex,nofollow">
		<link rel="stylesheet" href="github-markdown.css">

		<style>
			.markdown-body {
				box-sizing: border-box;
				min-width: 200px;
				max-width: 980px;
				margin: 0 auto;
				padding: 45px;
			}
		</style>
	</head>
	<body>
		<article class="markdown-body">
			<?theme body?>
		</article>
	</body>
</html>
